name: flutter_youtube_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bottom_sheet: ^4.0.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.2
  ffmpeg_kit_flutter: ^6.0.3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.5.0
  fraction: ^5.0.2
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  timeago: ^3.6.0
  uuid: ^4.0.0
  video_editor: ^3.0.0
  video_player: ^2.7.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
